# Generated by Django 3.2.10 on 2023-03-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="duedate",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
