# Generated by Django 3.2.10 on 2023-03-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_duedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="duedate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
