# Generated by Django 3.2.10 on 2023-03-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20230319_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='duedate',
            new_name='dueDate',
        ),
    ]
